# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lee Howorko
tagline:          lhoworko
url:              "http://lhoworko.github.io"
paginate:         3
baseurl:          /
author:
  name:           Lee Howorko
  url:            "https://twitter.com/lhoworko"
  email:          "lhoworko@gmail.com"

# Custom vars
version:          1.0.0
github:           "https://github.com/lhoworko"
pages_list:
  Home:           '/'
  About:          '/about/'
  Archive:        '/archive/'
  GitHub:         'https://github.com/lhoworko'
